baseURL = 'https://libmerit.github.io/'
languageCode = 'fa-ir'
title = 'آزادی و شایسته‌سالاری مردمی'
disableKinds = ["taxonomyTerm", "categories", "tags", "xml", "sitemap"]
googleAnalytics = "G-Y335TJ1F7Q"
enableRobotsTXT = true

[Params]
ogDescription= "در این کتاب نوعی ساختار حکومتی ماتریسی را طراحی و تشریح کرده‌ایم که نیاز به وجود هیچگونه رهبری ندارد، ایدئولوژی خاصی را برای مردم انتخاب نمی‌کند، ولی همواره متحد می‌ماند و در راستای انتظارات جامعه حرکت می‌کند."